### ISSUE TITLE
Change elem for color-picker

### ISSUE THREAD

**Issue by mateolaporte** [inakineitor/touch-bar-utility#10]
Hello I know it sounds like a dumb question... but how are you using the "change" and "selectedColor" events for the color picker... Documentation isn't really clear...
Many thanks

**Comment by inakineitor** [comment]
I updated the configuration system and added an example for a color-picker to the default configuration, but here is how you can do it with the new system:

`{
type: 'color-picker',
availableColors: ['#2fd2c1', '#be83c7', '#ac9df7'],
selectedColor: '#be83c7',
change: (color) => {
console.log(color);
}
}`

**Comment by mateolaporte** [comment]
Awesome ! Thanks a lot
