### ISSUE TITLE
Configuration not clear?

### ISSUE THREAD

**Issue by monkwooo** [inakineitor/touch-bar-utility#11]
which one of these works
`export default const configuration = [{
  type: 'label',
  label: 'touch-bar-utility rocks! 🤘🎸'
}]`

`exports.configuration = [{
  type: 'label',
  label: 'touch-bar-utility rocks! 🤘🎸'
}]`

`module.export = {
 configuration: [{
  type: 'label',
  label: 'touch-bar-utility rocks! 🤘🎸'
 }]
}`

`export {
 configuration: [{
  type: 'label',
  label: 'touch-bar-utility rocks! 🤘🎸'
 }]
}`

I've tried all of 'em, none seems to work

-------------------
Debugged a little and it turns out, the `Packages > Touchbar Utility > Edit configuration` opens a file at './lib/configuration.js' which is whatever user directory is currently atom is opened with

**Comment by encodis** [comment]
Is there a way to have a global configuration then?

**Comment by nikarc** [comment]
It seems like the package is looking for the configuration file in `~/.atom/packages/touchbar-utility/lib`, but when clicking on `Packages > Touch Bar Utility > Edit Configuration` its opening a config file local to the project.

I was able to get it working by changing the config file in `~/.atom/packages` and restarting atom.

**Comment by inakineitor** [comment]
I have performed the merge. In a few minutes I will publish it to APM.

**Comment by inakineitor** [comment]
I have performed the merge. In a few minutes I will publish it to APM.

**Comment by inakineitor** [comment]
I uploaded the new version (3.0.3) to APM. Thanks everyone. Now everything works!
