### ISSUE TITLE
New Update Old configuration gone, New one doesn't even try to display 

### ISSUE THREAD

**Issue by onelikeandidie** [inakineitor/touch-bar-utility#12]
<img width="776" alt="screen shot 2017-12-26 at 14 07 00" src="https://user-images.githubusercontent.com/33130521/34358261-180a701c-ea46-11e7-95b5-efb34ed9f08d.png">

It just doesn't work anymore it sets it to the default configuration

**Comment by inakineitor** [comment]
As stated in the text in the picture, the configuration no longer resides in the package's settings. Follow the instructions above in the image to change your configuration. Let me know if it worked.

**Comment by onelikeandidie** [comment]
![img_2311](https://user-images.githubusercontent.com/33130521/34378886-2a848034-eaf0-11e7-8bdc-9fc582217fab.JPG)
I have tried that now and it still doesn't work.
I've tried uninstalling and installing back and it also doesn't fix.
<img width="510" alt="screen shot 2017-12-27 at 10 21 57" src="https://user-images.githubusercontent.com/33130521/34378861-12acfebe-eaf0-11e7-8ba7-e8774b8bac0e.png">

**Comment by inakineitor** [comment]
I don't see a problem with your configuration. Could you please tell me your package version and the location of your configuration file.

**Comment by onelikeandidie** [comment]
`/Users/<user>/.atom/packages/touchbar-utility/lib/configuration.js`
Version of the package is `3.0.3`
I am using a Macbook Pro 2017 (of course)

**Comment by inakineitor** [comment]
I don't see anything wrong with your configuration. I don't understand what's happening. Try erasing the /Users/\<user\>/.atom/packages/touchbar-utility/ folder and reinstalling the package through APM.

**Comment by jirizavadil** [comment]
Hello @inakineitor, I have the same issue. After updating to 3.0.3, my settings went gone and I had to restore the package from Time Machine to get it. 

I believe the previous configuration was JSON, as requested in manual:
`[{
  "type": "button",
  "label": "//",
  "clickDispatchAction": "editor:toggle-line-comments",
  "backgroundColor": "#363636"
}, {
  "type": "button",
  "label": "/**",
  "clickDispatchAction": "editor:insert-docblockr",
  "backgroundColor": "#363636"
}, {
  "type": "button",
  "label": "tag",
  "clickDispatchAction": "wrap-in-tag:wrap",
  "backgroundColor": "#363636"
}, {
  "type": "button",
  "label": "beautify",
  "clickDispatchAction": "atom-beautify:beautify-editor",
  "backgroundColor": "#363636"
}, {
  "type": "button",
  "label": "terminal",
  "clickDispatchAction": "platformio-ide-terminal:toggle",
  "backgroundColor": "#363636"
}, {
  "type": "button",
  "label": "UI",
  "clickDispatchAction": "theme-toggler:toggle",
  "backgroundColor": "#363636"
}]
`

Looking at the new one, it appears to me as rather an object. So I rewrote it to this:
`exports.configuration = [{
  type: 'button',
  label: '//',
  clickDispatchAction: 'editor:toggle-line-comments',
  backgroundColor: '#363636'
}, {
  type: 'button',
  label: '/**',
  clickDispatchAction: 'editor:insert-docblockr',
  backgroundColor: '#363636'
}, {
  type: 'button',
  label: 'tag',
  clickDispatchAction: 'wrap-in-tag:wrap',
  backgroundColor: '#363636'
}, {
  type: 'button',
  label: 'beautify',
  clickDispatchAction: 'atom-beautify:beautify-editor',
  backgroundColor: '#363636'
}, {
  type: 'button',
  label: 'terminal',
  clickDispatchAction: 'platformio-ide-terminal:toggle',
  backgroundColor: '#363636'
}, {
  type: 'button',
  label: 'UI',
  clickDispatchAction: 'theme-toggler:toggle',
  backgroundColor: '#363636'
}]`

However, neither does work. Even after toggling with 'Activate'.


Atom: 1.23.2
touchbar-utility: 3.0.3
config path: /Users/jirizavadil/.atom/packages/touchbar-utility/lib/configuration.js

**Comment by jirizavadil** [comment]
Damn. Restart of Atom made it working. Sorry.

**Comment by onelikeandidie** [comment]
@inakineitor So after tries and tries I finally _"fixed"_ it. I used the _"Time Machine"_ then it didn't fix anything so I uninstalled the package but saved the settings I had and then installed it again but put my configuration and it works, it just works. **Papa Bless**. Great Package tho.

**Comment by inakineitor** [comment]
Thank you very much! I hope you continue to enjoy it. I'm closing the issue.
