### ISSUE TITLE
Not reflecting changes to `configuration.js` in touchbar

### ISSUE THREAD

**Issue by ProLoser** [inakineitor/touch-bar-utility#16]
I keep disabling/enabling and toggling the active checkbox for the plugin and nothing seems to reflect my edits to `configuration.js`. Only restarting atom reflects changes. Am I doing something wrong?

Atom v1.24.0 
OSX v10.12.6

**Comment by inakineitor** [comment]
I just realised. The reason it doesn't work is that that the configuration is cached the first time it is read. I have tried programmatically deleting the cache, but I've been unsuccessful. If you don't want to restart Atom, you could just reload the current window by doing `⌃⌥⌘L`.
