### ISSUE TITLE
How to dispatch multiple actions?

### ISSUE THREAD

**Issue by phdog** [inakineitor/touch-bar-utility#19]
is there a way for function called on 'click' to receive this clickDispatchAction method as an argument?
Need a way to dispatch multiple actions in a sequence

**Comment by inakineitor** [comment]
I think I know how I can implement it. I will try it and let you.

**Comment by inakineitor** [comment]
I have added this functionality in the new version. I will publish it in a few hours.
You will have to call the provided function dispatchAction multiple times from the click function of a button:
```
{
    type: 'button',
    label: 'Beautify and Comment',
    click: () => {
      dispatchAction('atom-beautify:beautify-editor');
      dispatchAction('editor:toggle-line-comments');
    },
    backgroundColor: '#e3e262'
  }
```

**Comment by phdog** [comment]
Thank you! One more thing: updating the package erased my existing configuration )) Would be great to avoid in n future)
PS The application I personally find useful: Comparison mode, which toggles tree-view, toggles minimap and splits panes side by side for 2 files
