### ISSUE TITLE
Packages events not working

### ISSUE THREAD

**Issue by phdog** [inakineitor/touch-bar-utility#20]
After your update packages other than editor do not receive actions, while keep working with hotkeys. For instance, 'platformio-ide-terminal:toggle'
I get this in Atom console
dispatchAction.js? [sm]:57 Uncaught (in promise) ReferenceError: clog is not defined
    at PackageManager.activatePackage.then.NotificationManager.addFatalError.dismissable (dispatchAction.js? [sm]:53)
    at <anonymous>

**Comment by inakineitor** [comment]
I have fixed it the new update. Make sure to make a copy of your configuration before updating. From this version onwards, the backup will be automatic, so you will never have to make a manual backup again.
Will be uploading the update in a few minutes.

**Comment by phdog** [comment]
Great! Thank you
