### ISSUE TITLE
Octicons support?

### ISSUE THREAD

**Issue by ProLoser** [inakineitor/touch-bar-utility#21]
I realize this may be a very complicated request. I'd like to be able to use octicons rather than just unicode icons so that it coincides with the atom theme. If you have suggestions on a good way to do this (since unfortunately Atom doesn't package the icons as images, instead using a font) would be interested.

**Comment by inakineitor** [comment]
As you said, Atom packages octicons as a font. For this reason, they can only be used as such in the HTML underlying the editor. I have found kind of a solution: [http://fa2png.io/r/octicons/](http://fa2png.io/r/octicons/) and for other fonts [http://fa2png.io/fonts/](http://fa2png.io/fonts/)
This site allows you to choose any icon, then select the export options and download it as the image. The image can then be used for the TouchBar.
