### ISSUE TITLE
Execute logic when entering / exiting popover

### ISSUE THREAD

**Issue by ProLoser** [inakineitor/touch-bar-utility#23]
I would like to have a popover group that when I enter the popover of controls for say a panel, I can execute a command to open the panel. Then I can select different commands for that respective panel and when I'm done I can (optionally) execute some logic upon exiting the popover to hide that panel.

**Comment by inakineitor** [comment]
Sadly, I don't think that is possible. My package adds functionality and high-level options over the [Touch Bar API provided by Electron](https://github.com/electron/electron/blob/master/docs/api/touch-bar-popover.md).
As the API has no hook or callback that is executed when the popover is closed or opened, I don't have any native functionality to expand to be able to achieve what you want.

**Comment by ProLoser** [comment]
Hopefully https://github.com/electron/electron/issues/12838 picks up some traction

**Comment by inakineitor** [comment]
Hopefully it does. For now, I'm keeping the issue closed. Feel free to reopen it if the functionality is added to Electron.
