### ISSUE TITLE
change-case package not working with buttons

### ISSUE THREAD

**Issue by bcaddy** [inakineitor/touch-bar-utility#26]
I mapped the change-case commands for switching between upper and lower case but I get the attached error whenever I try to use it.  I've also attached the relevant part of the config file.
<img width="460" alt="screen shot 2018-09-08 at 18 28 11" src="https://user-images.githubusercontent.com/41171425/45259210-51e10300-b395-11e8-8633-8ab41f38b77d.png">
<img width="575" alt="screen shot 2018-09-08 at 18 28 29" src="https://user-images.githubusercontent.com/41171425/45259211-51e10300-b395-11e8-88fd-1ba44185389e.png">

**Comment by inakineitor** [comment]
For some unknown reason, the change-case package is detected as uninstalled. You can refer to [this issue](https://github.com/inakineitor/touch-bar-utility/issues/25) for a solution.
You will need to override the package installation check and change the target to editor.
Your adapted code will look something like this:
```
{
  type: 'button',
  pathOfIcon: '/Users/Bob/Pictures/Icons/NSTouchBarGoUpTemplate.png',
  iconPosition: 'overlay',
  click: () => {
    dispatchAction('change-case:upper', 'editor', true);
  },
  backgroundColor: '#990000'
}, {
  type: 'button',
  pathOfIcon: '/Users/Bob/Pictures/Icons/NSTouchBarGoDownTemplate.png',
  iconPosition: 'overlay',
  click: () => {
    dispatchAction('change-case:lower', 'editor', true);
  },
  backgroundColor: '#990000'
}
```

**Comment by bcaddy** [comment]
Thanks!
