### ISSUE TITLE
Some package commands not working

### ISSUE THREAD

**Issue by SaintSimmo** [inakineitor/touch-bar-utility#5]
For example, my auto indent command "auto-indent:apply" wasn't working. I think it's because the dispatch call was being passed the wrong target. On lib/touch-bar-utility.js (line 143) I changed 

`atom.commands.dispatch(atom.views.getView(atom.workspace), atomPackage + ":" + packageEvent);`

to 

`atom.commands.dispatch(atom.views.getView(atom.workspace.getActiveTextEditor()), atomPackage + ":" + packageEvent);`

And this seems to have fixed my problems.

**Comment by inakineitor** [comment]
Right now I can't, but in a few days I will try to implement this with a check for undefined results (In case there is no editor).

**Comment by inakineitor** [comment]
I have coded the undefined checking and it now works fine. When I can I will update the package. I am not currently with a computer which I can use to upload it.

**Comment by inakineitor** [comment]
I have updated the package. The new package version is 2.0.11. Thank you for your collaboration.
