### ISSUE TITLE
icon paths?

### ISSUE THREAD

**Issue by rubenalcala** [inakineitor/touch-bar-utility#6]
TypeError: Cannot read property 'createFromPath' of undefined

**Comment by inakineitor** [comment]
Could you please show me your configuration, or has it never been changed?

**Comment by rubenalcala** [comment]
`[{"type": "button", "label": "Beautify","iconPosition":"left","pathOfIcon":"/Users/rubenalcala/Documents/touchbar/beauty.png","clickDispatchAction": "atom-beautify:beautify-editor"}]`

**Comment by inakineitor** [comment]
It think I have solved the issue. It ocurred while importing the nativeImage class. Please check if the error still exists in the new 2.0.11 updated version.

**Comment by inakineitor** [comment]
I have finally been able to test it. It now works.
