### ISSUE TITLE
How to triggle "new file" action?

### ISSUE THREAD

**Issue by xjkdev** [inakineitor/touch-bar-utility#8]
If i want to triggle new file action, what can i write in the clickdispatchAction field? or Is there any way to do this thing?

**Comment by patxu** [comment]
In a similar vein, I want to trigger other actions outside of Packages. Is this supported either by this package or at all by Atom?

**Comment by inakineitor** [comment]
If you want to create a new file, you should install the tree-view package. https://atom.io/packages/tree-view
In the clickdispatchAction field you should put "tree-view:add-file".

**Comment by inakineitor** [comment]
@patxu What do you mean by actions outside of packages? Internal Atom commands?

**Comment by goi42** [comment]
Similar question: I can't figure out how to do things like "pane:split-right". If I assign it as a "clickDispatchAction" it complains there is no "pane" package. If I assign it as a "click", it gives an error saying that "click" can only correspond to functions.

**Comment by inakineitor** [comment]
I fixed the issue. Update to the latest release and set the button's dispatchActionTarget to "editor".
