### ISSUE TITLE
(Question) Put specific char with a button

### ISSUE THREAD

**Issue by tomraulet** [inakineitor/touch-bar-utility#9]
Hi there,

I would like to add |, [ and ] shortcut button to my touchbar, but I'm unable to find which command I should use to make button write these specials characters in editor, any idea ?

Thanks

**Comment by inakineitor** [comment]
I added a property to buttons in the latest release (v2.5.1). Read about the 'insertString' property in the documentation. It works for me, so I'm closing the issue, but if doesn't work for you, feel free to reopen it.
